tick_distance = 0.01
gravity = 5
bounciness = 0.3
friction = 5
finish_radius = 0.2

[sfx]
master_volume = 3
music_volume = 0.3
scaling_max_volume = 1
hit_max_volume_speed = 3
hit_volume = 0.5
level_volume = 0.15
win_volume = 0.15

[camera]
fov = 10
speed = 2

[static]
max_vel = 0.1
time_to_full = 1

[level_mesh]
max_distance = 0.05

[player]
radius = 0.1
min_radius = 0.1
max_radius = 0.5
scaling_speed = 4

[cursor]
hotspot = [16, 16]

[editor]
snap_distance = 0.2
cursor_rotation_speed = 360
camera_speed = 5
