fov = 10
gravity = 5
bounciness = 0.3
friction = 0.9

[static]
max_vel = 0.1
time_to_full = 1

[level_mesh]
max_distance = 0.05

[player]
radius = 0.05
min_radius = 0.05
max_radius = 0.5
scaling_speed = 5

[cursor]
hotspot = [16, 16]

[editor]
snap_distance = 0.2
cursor_rotation_speed = 360
